### ISSUE TITLE
Banner aanmaken

### ISSUE THREAD

**Issue by TeppersBen** [Activisme-be/Barebones#11]
Deze ticket is aangemaakt in opdracht van @alfamongrel , Reminder dat er een banner gemaakt moet worden voor de eerst volgende crowdfund.

@alfamongrel neemt dit volledig in handen.

**Comment by Tjoosten** [comment]
Hi @TeppersBen of @alfamongrel  zou je een ticket beschrijving kunnen aanmaken wanneer je de tijd ervoor hebt?

**Comment by Tjoosten** [comment]
@alfamongrel status update aub.
