### ISSUE TITLE
Splits de documentatie uit de source files.

### ISSUE THREAD

**Issue by Tjoosten** [Activisme-be/Barebones#8]
Documentatie zou wegens bloat in de programmatuur gesplitst moeten worden. In aparte markdown files. die worden onder gebracht in `/docs` 

Ik stel voor dat ik de repo in gereedheid zet. Zodat jij de documentatie kunt splitten?

**Comment by TeppersBen** [comment]
@Tjoosten Is goed voor mij, wil je ook laten weten dat 5 mei de laatste les-maand is ingegaan en ik nu druk bezig ben met het maken van projecten en presentaties. vanaf 5 juni gaat mijn examen maand in.

dus bij deze ben je op de hoogte.

**Comment by Tjoosten** [comment]
Dank je voor het melden. Ik stel voor dat ik issues ondertussen blijf
aanmaken. Maar dat jij eerst je examens en les knalt. :) En moest ik het vergeten in Juni alvast success met je examens.

Mvg,
Tim Joosten

Op 8 mei 2017 om 12:09 schreef Ben Teppers <notifications@github.com>:

**Comment by Tjoosten** [comment]
@TeppersBen Is het goed dat ik je unassign van het ticket. Zodat ik dit ticket kan overnemen?

**Comment by TeppersBen** [comment]
@Tjoosten ik heb hoogstwaarschijnlijk deze mention-mail niet gezien door het hoge aantal spam dat wij van school binnen krijgen.

je mag deze van mij overnemen.

**Comment by Tjoosten** [comment]
Geen probleem :)

Op 18 mei 2017 om 10:43 schreef Ben Teppers <notifications@github.com>:
